---
- name: Download TLAToolbox
  get_url:
    url: "https://github.com/tlaplus/tlaplus/releases/download/v{{ tlaplus_version }}/{{ linux_tlaplus_zip }}"
    dest: "/tmp/{{ linux_tlaplus_zip }}"
    checksum: "{{ linux_tlaplus_checksum }}"

- name: Unarchive a file
  unarchive:
    src: "/tmp/{{ linux_tlaplus_zip }}"
    dest: /Applications

- file:
    path: "/tmp/{{ linux_tlaplus_zip }}"
    state: absent
